# Generated by Django 3.1.6 on 2021-02-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(max_length=10)),
                ('category', models.CharField(choices=[('Восточная кухня', 'Восточная кухня'), ('Европейская кухня', 'Европейская кухня'), ('Десерты', 'Десерты'), ('Напитки', 'Напитки'), ('Салаты', 'Салаты')], max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
