# Generated by Django 3.1.6 on 2021-02-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20210218_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default='team_image.png', null=True, upload_to=''),
        ),
    ]
