# Generated by Django 3.1.6 on 2021-02-18 11:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe', '0009_auto_20210218_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Client',
        ),
    ]
