# Generated by Django 3.1.6 on 2021-02-19 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_auto_20210218_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('author', models.TextField()),
                ('date', models.DateField(default=datetime.date(2021, 2, 19))),
                ('comments', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
