# Generated by Django 3.1.6 on 2021-02-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0016_auto_20210219_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='large_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
