# Generated by Django 3.1.6 on 2021-02-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0017_blog_large_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='large_title',
            field=models.TextField(max_length=200),
        ),
    ]
