# Generated by Django 3.1.6 on 2021-02-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0019_auto_20210221_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
