# Generated by Django 3.1.6 on 2021-02-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0023_auto_20210227_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
