# Generated by Django 3.1.6 on 2021-02-27 14:28

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0025_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=django.contrib.auth.models.User),
        ),
    ]
