# Generated by Django 3.1.6 on 2021-02-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0026_auto_20210227_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
