# Generated by Django 3.1.6 on 2021-02-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0027_auto_20210227_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='email',
        ),
    ]
